config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :universes, only: %i[index show]
  resources :storyrooms, only: %i[index show new create edit update destroy] do
    resources :storyroom_characters, only: %i[new create edit update destroy]
    resources :messages, only: %i[create edit update]
    resources :storycards, only: %i[create destroy]
    resources :events, only: %i[create]
  end
  resources :history, only: %i[index show]
end

app/models/storyroom_character.rb
class StoryroomCharacter < ApplicationRecord
  belongs_to :storyroom
  belongs_to :user
  validates :storyroom, presence: true
  validates :user, presence: true

  validates :user_id, uniqueness: { scope: :storyroom_id, message: "ne peut avoir qu'un seul personnage par storyroom" }
end

app/controllers/storyroom_characters_controller.rb
class StoryroomCharactersController < ApplicationController

  def new
    @storyroom = Storyroom.find(params[:storyroom_id])
    @universe = @storyroom.universe
    @characters = @universe.characters
    @storyroom_character = StoryroomCharacter.new
    @close_users = Set.new
    current_user.storyroom_characters.each do |storyroom_character|
      user = User.find(storyroom_character.storyroom.user_id)
      @close_users << user if user != current_user
    end
  end

  def create
    @storyroom = Storyroom.find(params[:storyroom_id])
    @user = User.find_by(username: params[:username])

    @character = Character.find(params[:character_id])
    @storyroom_character = StoryroomCharacter.new
    @storyroom_character.storyroom = @storyroom
    @storyroom_character.photo = @character.photo
    @storyroom_character.name = @character.name
    @storyroom_character.quotation = @character.quotation
    @storyroom_character.background = @character.background
    @storyroom_character.user = @user
    if @storyroom_character.save
      redirect_to storyroom_path(@storyroom)
    else
      @universe = @storyroom.universe
      @characters = @universe.characters
      @close_users = []
      current_user.storyroom_characters.each do |storyroom_character|
        @close_users << User.find(storyroom_character.storyroom.user_id) if User.find(storyroom_character.storyroom.user_id) != current_user
      end
      render :new
    end
  end


  def edit
    @storyroom = Storyroom.find(params[:storyroom_id])
    @storyroom_character = StoryroomCharacter.find(params[:id])
  end

  def update
    @storyroom_character = StoryroomCharacter.find(params[:id])
    @storyroom_character.update(
      name: storyroom_character_params[:storyroom_character_name],
      quotation: storyroom_character_params[:storyroom_character_quotation],
      background: storyroom_character_params[:storyroom_character_background]
    )
    @storyroom = Storyroom.find(@storyroom_character.storyroom_id)
    redirect_to storyroom_path(@storyroom)
  end


  def destroy
    @storyroom = Storyroom.find(params[:storyroom_id])
    @storyroom_character = StoryroomCharacter.find(params[:id])
    @storyroom_character_user = @storyroom_character.user
    @storyroom_user_messages = @storyroom.messages.where( user: @storyroom_character_user)
    @storyroom_user_messages.each do |message|
      message.destroy
    end
    @storyroom_character.destroy

    if current_user == @storyroom.user
      redirect_to storyroom_path(@storyroom)
    else
      redirect_to storyrooms_path
    end
  end

  private

  def storyroom_character_params
    params.require(:storyroom_character).permit(
      :storyroom_id,
      :character_id,
      :username,
      :storyroom_character_name,
      :storyroom_character_quotation,
      :storyroom_character_background,
    )
  end

end

app/helpers/storyroom_characters_helper.rb
module StoryroomCharactersHelper
end

app/views/storyroom_characters/edit.html.erb
<%= link_to storyroom_path(@storyroom), class:"topbar_back_button" do %>
  <i class="fa-solid fa-angle-left"></i>
<% end %>

<div class="storyroomcharacter_img" style="background-image: url(<%= @storyroom_character.photo %>);">
</div>

<div class="storyroom_newtail">
  <%= form_with model: [@storyroom, @storyroom_character] do |form| %>
    <div>
      <%= form.label :storyroom_storyroom_characters, "Modifier" %>
      <%= form.text_field :storyroom_character_name, value: @storyroom_character.name, class: "textfield_custom" %>
      <%= form.text_field :storyroom_character_quotation, value: @storyroom_character.quotation, class: "textfield_custom" %>
      <%= form.text_area :storyroom_character_background, value: @storyroom_character.background, rows: 10, class: "textarea_custom" %>
    </div>

    <%= button_tag(type: 'submit') do %>
      <i class="fa-regular fa-floppy-disk"></i>
    <% end %>

  <% end %>
</div>

app/views/storyroom_characters/new.html.erb
<%= link_to storyroom_path(@storyroom), class:"topbar_back_button" do %>
  <i class="fa-solid fa-angle-left"></i>
<% end %>

<div class="storyroom_card" style="background-image: linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0) 75%), url(<%= @universe.photo %>);">
  <h2><%= @storyroom.title[0..50] %></h2>
  <p><%= @storyroom.universe.title %></p>
  <div class="storyroom_universe_btn">
  </div>
</div>

<div data-controller="storyroom-characters">
  <div class="universe_characters">
    <h2>Les personnages à incarner</h2>
    <div class="caroussel_btn">
      <button data-action="storyroom-characters#previousCharacter" data-storyroom-characters-target="previousCharacterButton"><i class="fa-solid fa-angle-left"></i></button>
      <button data-action="storyroom-characters#randomCharacter" data-storyroom-characters-target="randomCharacterButton"><i class="fa-solid fa-dice-d20"></i></button>
      <button data-action="storyroom-characters#nextCharacter" data-storyroom-characters-target="nextCharacterButton"><i class="fa-solid fa-angle-right"></i></button>
    </div>
    <% @characters.each do |character| %>
      <div class="universe_character" data-storyroom-characters-target="universeCharacter" data-id="<%= character.id %>">
        <div class="character_top">
          <div class="character_img" style="background-image: url(<%= character.photo %>);">
          </div>
          <div class="character_info">
            <h3><%= character.name %></h3>
            <p><%= character.age ? "#{character.age} ans" : "" %></p>
            <p><em>"<%= character.quotation %>"</em></p>
          </div>
        </div>
        <div class="character_description">
          <p><%= character.background %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="paragraphe_container" data-controller="storyroom-new-characters">

    <p>Inscivez un nom d'utilisateur</p>

      <div class="invite_user">
        <%= form_with url: storyroom_storyroom_characters_path(@storyroom), method: :post, id: "storyroom-form" do %>
          <%= text_field_tag :username, nil, label: "username", id: "username-id-field", "data-storyroom-new-characters-target" => "usernameIdField", class: "textfield_custom" %>
          <%= hidden_field_tag :character_id, "", id: "character-id-field", "data-storyroom-characters-target" => "characterIdField" %>
          <%= button_tag type: "submit", class: "floating-button" do %>
            <i class="fa-solid fa-user-plus"></i>
          <% end %>
        <% end %>
      </div>
      <% if @close_user %>
        <h2>Suggestions</h2>
        <div class="suggested_usernames">
          <% @close_users.each do |close_user| %>
            <p data-storyroom-new-characters-target="usernameSuggested" data-action="click->storyroom-new-characters#pasteUsername" ><%= close_user.username %></p>
          <% end %>
      <% else %>
        <h2>_</h2>
      <% end %>
    </div>
  </div>
</div>