config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :universes, only: %i[index show]
  resources :storyrooms, only: %i[index show new create edit update destroy] do
    resources :storyroom_characters, only: %i[new create edit update destroy]
    resources :messages, only: %i[create edit update]
    resources :storycards, only: %i[create destroy]
    resources :events, only: %i[create]
  end
  resources :history, only: %i[index show]
end

app/models/storyroom.rb
class Storyroom < ApplicationRecord
  belongs_to :universe
  belongs_to :user
  # has_many :messages
  # has_many :storyroom_user_associations
  # has_many :users, through: :storyroom_user_associations
  # has_many :events
  # has_many :words, through: :events
  # has_many :storycards
  # has_many :storyroom_characters
  # validates :title, presence: true, uniqueness: { scope: :universe }
  # validates :user, presence: true
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :storycards, dependent: :destroy
  has_many :storyroom_characters, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: :universe }
end

app/controllers/storyrooms_controller.rb
class StoryroomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @storyrooms = Storyroom.where(user: current_user).order(created_at: :desc)
    @groups = []
    current_user.storyroom_characters.each do |storyroom_character|
      @groups << storyroom_character.storyroom if storyroom_character.storyroom.user != current_user
    end
    @groups.sort_by! { |group| group.created_at }.reverse!
  end


  def show
    @storyroom = Storyroom.find(params[:id])
    @title = @storyroom.title
    @universe = @storyroom.universe
    @storycards = @storyroom.storycards
    @messages = @storyroom.messages
    @events = @storyroom.events
    @characters = @storyroom.universe.characters
    @words = @storyroom.universe.words

    @timeline_items = (@storyroom.events + @storyroom.messages).sort_by(&:created_at).reverse

    @storyroom_characters = @storyroom.storyroom_characters.sort_by(&:created_at)

    @message = Message.new
  end

  def new
    @storyroom = Storyroom.new
    @universe = Universe.find(params[:universe_id])
    @synopsis = Synopsis.find(params[:synopse_id])
    @character = Character.find(params[:character_id])
    @title = @universe.title
    @words = @universe.words
  end


  def create
    # création de la salle de jeu
    @synopsis = Synopsis.find(params[:storyroom][:storyroom_synopsis_original_id])
    @character = Character.find(params[:storyroom][:storyroom_character_original_id])
    @storyroom = Storyroom.new
    @universe = Universe.find(params[:storyroom][:universe_id])
    @storyroom.universe = @universe
    @storyroom.user = current_user
    @storyroom.title = params[:storyroom][:title]
    @storyroom.storyroom_synopsis = params[:storyroom][:storyroom_synopsis]

    # création du personnage
    @storyroom_character = StoryroomCharacter.new(storyroom: @storyroom, user: current_user)
    @storyroom_character.name = params[:storyroom][:storyroom_character_name]
    @storyroom_character.quotation = params[:storyroom][:storyroom_character_quotation]
    @storyroom_character.background = params[:storyroom][:storyroom_character_background]
    @storyroom_character.photo = params[:storyroom][:storyroom_character_photo]

    if @storyroom.save
      # création du personnage
      @storyroom_character.storyroom = @storyroom
      @storyroom_character.save

      # création des cartes de mots associées au monde
      @universe.words.each do |word|
        @storycard = Storycard.new
        @storycard.title = word.title
        @storycard.storyroom = @storyroom
        @storycard.save
      end


      redirect_to storyroom_path(@storyroom)
    else
      render :new
    end
  end

  def edit
    @storyroom = Storyroom.find(params[:id])
    @title = @storyroom.title
    @universe = @storyroom.universe
    @storyroom_synopsis = @storyroom.storyroom_synopsis
    @storyroom_character = StoryroomCharacter.find_by(storyroom: @storyroom, user: current_user)
  end

  def update
    @storyroom = Storyroom.find(params[:id])
    @storyroom.update(
      title: params[:storyroom][:title],
      storyroom_synopsis: params[:storyroom][:storyroom_synopsis])

    redirect_to storyroom_path(@storyroom)
  end

  def destroy
    @storyroom = Storyroom.find(params[:id])
    if @storyroom.destroy
      flash[:notice] = "Storyroom has been deleted successfully."
    else
      flash[:alert] = "There was an error deleting the Storyroom."
    end
    redirect_to storyrooms_path
  end



  private

  def storyroom_params
    params.require(:storyroom).permit(
      :title,
      :universe_id,
      :storyroom_synopsis_original_id,
      :storyroom_synopsis,
      :storyroom_character_original_id,
      :storyroom_character_name,
      :storyroom_character_quotation,
      :storyroom_character_background,
      :storyroom_character_photo
    )
  end
end

app/helpers/storyrooms_helper.rb
module StoryroomsHelper
end

app/views/storyrooms/_lore.html.erb
<% if @storyroom.user == current_user %>
  <div class="storyroom_edit_icon">
    <%= button_to storyroom_path(@storyroom), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="fa-regular fa-trash-can"></i>
    <% end %>
    <%= link_to new_storyroom_storyroom_character_path(@storyroom), id: "add_user" do%>
      <i class="fa-solid fa-user-plus"></i>
    <% end %>
    <%= link_to edit_storyroom_path(@storyroom), method: :get do %>
      <i class="fa-regular fa-pen-to-square"></i>
    <% end %>
  </div>
<% end %>


<div class="paragraphe_container">
  <h2>L'univers de <%= @storyroom.universe.title %></h2>
  <p><%= @storyroom.universe.description %></p>
</div>

<div class="paragraphe_container">
  <h2>Le scénario du récit</h2>
  <p><%= @storyroom.storyroom_synopsis %></p>
</div>

<div class="universe_characters">
  <% if @storyroom.storyroom_characters.count == 1 %>
    <h2>Le personnage</h2>
  <% else %>
    <h2>Les personnages</h2>
  <% end %>
  <% @storyroom_characters.each do | storyroom_character | %>
    <div class="universe_character selected">
      <div class="character_top">
        <div class="character_img" style="background-image: url(<%= storyroom_character.photo %>);">
        </div>
        <div class="character_info">
          <h3>
            <%= storyroom_character.name %>
            <% if storyroom_character.user == @storyroom.user %>
              <i class="fa-solid fa-crown" id="owner_crown"></i>
            <% end %>
          </h3>
          <p><em>"<%= storyroom_character.quotation %>"</em></p>
        </div>
      </div>
      <div class="character_description">
        <p><%= storyroom_character.background %></p>
        <p>- <%= storyroom_character.user.username %> -</p>
      </div>
      <div class="manage_character_btn">
        <% if storyroom_character.user == current_user %>
          <% if storyroom_character.user != @storyroom.user %>
            <%= button_to storyroom_storyroom_character_path(@storyroom, storyroom_character), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa-solid fa-skull-crossbones"></i>
            <% end %>
          <% end %>
          <%= link_to edit_storyroom_storyroom_character_path(@storyroom, storyroom_character), method: :get do %>
            <i class="fa-regular fa-pen-to-square"></i>
          <% end %>
        <% elsif @storyroom.user == current_user && storyroom_character.user != @storyroom.user%>
          <%= button_to storyroom_storyroom_character_path(@storyroom, storyroom_character), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa-solid fa-skull-crossbones"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/storyrooms/_story.html.erb
<% if @storyroom.events.count == 0 %>
  <div class="infos_container" id="infos">
    <p><i>Comme dans un journal, racontez successivement des morceaux d'histoire dans cet univers.
    <br>Lancez le D20 <i class="fa-solid fa-dice-d20"></i> pour un élan d'inspiration!</i></p>
  </div>

  <div class="paragraphe_container">
    <p><%= @storyroom.storyroom_synopsis %></p>
  </div>
<% end %>

<div class="storyroom_messages">
  <% @timeline_items.each do |item| %>
    <% if item.is_a? Event %>
      <div class="event_announcement">
        <p><b><%= item.word.title %></b></p>
        <i class="fa-solid fa-dice-d20"></i>
        <p><b><%= item.description %></b></p>
      </div>
    <% elsif item.is_a? Message %>
    <%# les messages ---------------------------------------- %>
    <% if StoryroomCharacter.find_by(storyroom: @storyroom, user: item.user) %>
        <div class="messages_infos">
          <p><%= l(item.created_at.in_time_zone("Paris"), format: "%d %B %Y, %H:%M") %></p>
          <div class="character_user_picture" style="background-image: url(<%= StoryroomCharacter.find_by(storyroom: @storyroom, user: item.user).photo %>);">
          </div>
          <p><%= StoryroomCharacter.find_by(storyroom: @storyroom, user: item.user).name %></p>
        </div>
          <% if current_user == item.user %>
            <div class="message_current_user">
                <p><%= item.content %></p>
                <%= link_to edit_storyroom_message_path(@storyroom, item), method: :get do %>
                  <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
            </div>
          <% else %>
            <div class="message_other_user">
              <p><%= item.content %></p>
            </div>
          <% end %>
    <% end %>
    <% end %>
  <% end %>
</div>

<div class="message_bar_container focused">
  <div class="message_bar" data-controller="messagebar">
    <div class="division_bar">
    </div>
    <div class="event_counter">
      <% if @storycards.count > 0 %>
        <p><%= @storycards.count %></p>
        <%= button_to storyroom_events_path(@storyroom), method: :post do %>
          <i class="fa-solid fa-dice-d20"></i>
        <% end %>
      <% else %>
        <h2>Fin</h2>
      <% end %>
    </div>

    <div class="message_typing ">
      <%= form_for [@storyroom, @message] do |f| %>
        <%= f.text_field :content, data: { messagebar_target: "messageField"}, class: "textfield_custom" %>
        <%= button_tag(type: 'submit') do %>
          <i class="fa-solid fa-feather"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/storyrooms/edit.html.erb
<%= link_to storyroom_path(@storyroom), class:"topbar_back_button" do %>
  <i class="fa-solid fa-angle-left"></i>
<% end %>

<div class="universe_card" style="background-image: linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0) 75%), url(<%= @universe.photo %>);">
  <h2><%= @universe.title %></h2>
  <p><%= @universe.description.split('.').first %>.</p>
</div>

<div class="paragraphe_container">
  <p>Modifiez comme vous le désirez</p>
</div>

<div class="storyroom_newtail">
  <%= form_with model: @storyroom do |form| %>

    <div>
      <%= form.label :title, "Titre du récit" %>
      <%= form.text_field :title, value: @storyroom.title, class: "textfield_custom" %>
    </div>

    <div>
      <%= form.label :storyroom_synopsis, "Scénario" %>
      <%= form.text_area :storyroom_synopsis, value: @storyroom_synopsis, rows: 10, class: "textarea_custom" %>
    </div>

    <%= button_tag(type: 'submit') do %>
      <i class="fa-regular fa-floppy-disk"></i>
    <% end %>

  <% end %>
</div>

app/views/storyrooms/index.html.erb
<div data-controller="storyroom-index" class="storyroom_index">
  <div class="storyroom_index_btn">
    <button data-action="storyroom-index#showOwner" data-storyroom-index-target="owner_btn" class="selected" id="owner-button"><i class="fa-solid fa-crown"></i></button>
    <button data-action="storyroom-index#showGroups" data-storyroom-index-target="groups_btn" id="groups-button"><i class="fa-solid fa-user-group"></i></button>
  </div>


  <div data-storyroom-index-target="owner" class="owner selected">
    <% if @storyrooms.empty? %>
      <div class="paragraphe_container">
        <p>Commencez par sélectionner un univers pour débuter votre propre récit.<br><i class="fa-solid fa-feather"></i></p>
      </div>
    <% end %>
    <% @storyrooms.each do |storyroom| %>
      <% if storyroom.storycards.count != 0  %>
        <%= link_to storyroom_path(storyroom), class: "storyroom_card", style: "background-image: linear-gradient(0deg, #1B1C20 0%, rgba(0,0,0,0) 50%), url(#{storyroom.universe.photo});" do %>
          <h2><%= storyroom.title[0..50] %></h2>
          <div class="card_stats">
            <p><%= storyroom.universe.title %> </p>
            <p class="d20"><i class="fa-solid fa-dice-d20"></i> <%= storyroom.storycards.count %></p>
            <% if storyroom.storyroom_characters.count <= 1 %>
              <p><i class="fa-solid fa-user"></i> <%= storyroom.storyroom_characters.count %></p>
            <% else %>
              <p><i class="fa-solid fa-user-group"></i> <%= storyroom.storyroom_characters.count %></p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div data-storyroom-index-target="groups" class="groups">
      <% if @groups.empty? %>
        <div class="paragraphe_container">
          <p>Partagez votre "username" pour être invité dans d'autres récits</p>
        </div>
      <% end %>
      <% @groups.each do |group| %>
        <% if group.storycards.count != 0  %>
          <%= link_to storyroom_path(group), class: "storyroom_card", style: "background-image: linear-gradient(0deg, #1B1C20 0%, rgba(0,0,0,0) 50%), url(#{group.universe.photo});" do %>
            <h2><%= group.title[0..50] %></h2>
            <div class="card_stats">
              <p><%= group.universe.title %> </p>
              <p class="d20"><i class="fa-solid fa-dice-d20"></i> <%= group.storycards.count %></p>
              <% if group.storyroom_characters.count <= 1 %>
                <p><i class="fa-solid fa-user"></i> <%= group.storyroom_characters.count %></p>
              <% else %>
                <p><i class="fa-solid fa-user-group"></i> <%= group.storyroom_characters.count %></p>
              <% end %>
            </div>
        <% end %>
      <% end %>
    <% end %>
  </div>


</div>

app/views/storyrooms/new.html.erb
<%= link_to universe_path(@universe), class:"topbar_back_button" do %>
  <i class="fa-solid fa-angle-left"></i>
<% end %>


<div class="universe_card" style="background-image: linear-gradient(0deg, #1B1C20 0%, rgba(0,0,0,0) 50%), url(<%= @universe.photo %>);">
  <h2>Votre récit s'apprête à débuter ...</h2>
  <p><%= @universe.title %> - <%= @universe.description.split('.').first %></p>
</div>


<div class="storyroom_newtail">
  <%= form_with model: @storyroom do |form| %>
    <%= form.hidden_field :universe_id, value: @universe.id %>

    <div>
      <%= form.label :title, "Nommez votre récit" %>
      <%= form.text_field :title, class: "textfield_custom"%>
    </div>


    <div>
      <%= form.label :storyroom_synopsis, "Le scénario" %>
      <%= form.hidden_field :storyroom_synopsis_original_id, value: @synopsis.id%>
      <%= form.text_area :storyroom_synopsis, value: @synopsis.description, rows: 10, class: "textarea_custom" %>
      <%= form.hidden_field :storyroom_character_original_id, value: @character.id%>
      <%= form.hidden_field :storyroom_character_name, value: @character.name %>
      <%= form.hidden_field :storyroom_character_quotation, value: @character.quotation %>
      <%= form.hidden_field :storyroom_character_background, value: @character.background%>
      <%= form.hidden_field :storyroom_character_photo, value: @character.photo %>
    </div>


    <%= button_tag(type: 'submit') do %>
      <i class="fa-solid fa-feather"></i>
    <% end %>

    <div class="info_container">
      <p>Vous pourrez également modifier les personnages par la suite</p>
    </div>

  <% end %>
</div>

app/views/storyrooms/show.html.erb
<%= link_to storyrooms_path, class:"topbar_back_button" do %>
  <i class="fa-solid fa-angle-left"></i>
<% end %>

<div data-controller="storyroom" >
  <div class="storyroom_card" style="background-image: linear-gradient(0deg, #1B1C20 0%, rgba(0,0,0,0) 75%), url(<%= @universe.photo %>);">
    <h2><%= @storyroom.title[0..50] %></h2>
    <p><%= @storyroom.universe.title %></p>
    <div class="storyroom_universe_btn">
      <button data-action="storyroom#showStory" data-storyroom-target="story_btn" class="selected" id="story-button"><i class="fa-solid fa-feather"></i></button>
      <button data-action="storyroom#showLore" data-storyroom-target="lore_btn" id="lore-button"><i class="fa-solid fa-circle-plus"></i></button>
    </div>
  </div>

  <div data-storyroom-target="story" class="storyroom_story selected">
    <%= render'storyrooms/story' %>
  </div>

  <div data-storyroom-target="lore" class="storyroom_lore">
    <%= render'storyrooms/lore' %>
  </div>
</div>