config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :universes, only: %i[index show]
  resources :storyrooms, only: %i[index show new create edit update destroy] do
    resources :storyroom_characters, only: %i[new create edit update destroy]
    resources :messages, only: %i[create edit update]
    resources :storycards, only: %i[create destroy]
    resources :events, only: %i[create]
  end
  resources :history, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :universe_character_associations, dependent: :destroy
  has_many :universes, through: :universe_character_associations
  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :word
  belongs_to :storyroom
  validates :dice_value, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :storyroom
  belongs_to :user
  validates :content, presence: true
end

app/models/storycard.rb
class Storycard < ApplicationRecord
  belongs_to :storyroom
  validates :title, presence: true
end

app/models/storyroom.rb
class Storyroom < ApplicationRecord
  belongs_to :universe
  belongs_to :user
  # has_many :messages
  # has_many :storyroom_user_associations
  # has_many :users, through: :storyroom_user_associations
  # has_many :events
  # has_many :words, through: :events
  # has_many :storycards
  # has_many :storyroom_characters
  # validates :title, presence: true, uniqueness: { scope: :universe }
  # validates :user, presence: true
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :storycards, dependent: :destroy
  has_many :storyroom_characters, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: :universe }
end

app/models/storyroom_character.rb
class StoryroomCharacter < ApplicationRecord
  belongs_to :storyroom
  belongs_to :user
  validates :storyroom, presence: true
  validates :user, presence: true

  validates :user_id, uniqueness: { scope: :storyroom_id, message: "ne peut avoir qu'un seul personnage par storyroom" }
end

app/models/synopsis.rb
class Synopsis < ApplicationRecord
  belongs_to :universe
end

app/models/universe.rb
class Universe < ApplicationRecord
  # has_many :universe_word_associations
  # has_many :words, through: :universe_word_associations
  # has_many :universe_character_associations, dependent: :destroy
  # has_many :characters, through: :universe_character_associations
  has_many :words, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :synopses, dependent: :destroy
  validates :photo, presence: true
  validates :title, presence: true
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :storyroom_user_associations
  has_many :storyrooms, through: :storyroom_user_associations
  has_many :storyrooms
  has_many :storyroom_characters
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/models/word.rb
class Word < ApplicationRecord
  # has_many :universe_word_associations
  # has_many :universe, through: :universe_word_associations
  belongs_to :universe
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    @storyroom = Storyroom.find(params[:storyroom_id])
    @storycards = @storyroom.storycards
    @event = @storyroom.events.create
    @event.word = Word.find_by(title: @storycards.sample.title)
    @storycards.find_by(title: @event.word.title).destroy
    @event.dice_value = rand(1..20)
    @event.description = outcome(@event.dice_value)

    if @event.save
      redirect_to @storyroom
    else
      redirect_to @storyroom
    end
  end

  private

  def event_params
    params.require(:event).permit(:storyroom_id)
  end

  def outcome(dice_value)
    if dice_value <= 2
      'Echec critique'
    elsif dice_value <= 10
      'Négatif'
    elsif dice_value <= 18
      'Positif'
    elsif dice_value <= 20
      'Réussite critique'
    else
      'Neutre'
    end
  end

end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  before_action :authenticate_user!

  def index
    @storyrooms = Storyroom.where(user: current_user).order(created_at: :desc)
    @groups = []
    current_user.storyroom_characters.each do |storyroom_character|
      @groups << storyroom_character.storyroom if storyroom_character.storyroom.user != current_user
    end
    @groups.sort_by! { |group| group.created_at }.reverse!


    @ended_stories = []
    @storyrooms.each do |storyroom|
      @ended_stories << storyroom if storyroom.storycards.count == 0
    end
    @ended_stories = @ended_stories.sort_by { |storyroom| storyroom.updated_at }.reverse

    @ended_stories_groups = []
    @groups.each do |storyroom|
      @ended_stories_groups << storyroom if storyroom.storycards.count == 0
    end
    @ended_stories_groups = @ended_stories_groups.sort_by { |storyroom| storyroom.updated_at }.reverse
  end


  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  def index
    @universes = Universe.all.shuffle
  end

  def show
    @universe = Universe.find(params[:id])
    @synopses = @universe.synopses
    @short_description = @universe.description.split('.')[0]
    @words = @universe.words

    @characters = @universe.characters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/storyrooms_helper.rb
module StoryroomsHelper
end

app/helpers/universes_helper.rb
module UniversesHelper
end

app/views/universes/index.html.erb
<div class="universes_section" data-controller="hellouniverse">
  <div class="paragraphe_container">
    <h1>Les univers</h1>
    <a href=""><i class="fa-solid fa-dice-d20" id="rand_dice_univ_index"></i></a>
  </div>
  <% @universes.each do |universe| %>
    <%= link_to universe_path(universe), class: "universe_card", style: "background-image: linear-gradient(0deg, #1B1C20 0%, rgba(0,0,0,0) 50%), url(#{universe.photo});" do %>
      <h2><%= universe.title %></h2>
      <p><%= universe.description.split('.').first %>.</p>
      <div class="card_stats">
        <p><i class="fa-solid fa-book-open"></i> <%= universe.synopses.count %></p>
        <p><i class="fa-solid fa-user"></i> <%= universe.characters.count %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/universes/show.html.erb
<%= link_to universes_path, class:"topbar_back_button" do %>
  <i class="fa-solid fa-angle-left"></i>
<% end %>

<div class="universe_card" style="background-image: linear-gradient(0deg, #1B1C20 0%, rgba(0,0,0,0) 75%), url(<%= @universe.photo %>);">
  <h2><%= @universe.title %></h2>
  <p><%= @universe.description[0..500] %></p>
</div>



<div data-controller="universe">
  <div class="universe_synopses">
    <h2>Les scénarios</h2>
    <div class="caroussel_btn">
      <button data-action="universe#previousSynopsis" data-universe-target="previousSynopseButton"><i class="fa-solid fa-angle-left"></i></button>
      <button data-action="universe#randomSynopsis" data-universe-target="randomSynopseButton"><i class="fa-solid fa-dice-d20"></i></button>
      <button data-action="universe#nextSynopsis" data-universe-target="nextSynopseButton"><i class="fa-solid fa-angle-right"></i></button>
    </div>
    <% @synopses.each do |synopse| %>
      <div class="universe_synopse" data-universe-target="universeSynopse" data-id="<%= synopse.id %>">
        <p><%= synopse.description %></p>
      </div>
    <% end %>
  </div>

  <div class="universe_characters">
    <h2>Les personnages à incarner</h2>
    <div class="caroussel_btn">
      <button data-action="universe#previousCharacter" data-universe-target="previousCharacterButton"><i class="fa-solid fa-angle-left"></i></button>
      <button data-action="universe#randomCharacter" data-universe-target="randomCharacterButton"><i class="fa-solid fa-dice-d20"></i></button>
      <button data-action="universe#nextCharacter" data-universe-target="nextCharacterButton"><i class="fa-solid fa-angle-right"></i></button>
    </div>
    <% @characters.each do |character| %>
      <div class="universe_character" data-universe-target="universeCharacter" data-id="<%= character.id %>">
        <div class="character_top">
          <div class="character_img" style="background-image: url(<%= character.photo %>);">
          </div>
          <div class="character_info">
            <h3><%= character.name %></h3>
            <p><%= character.age ? "#{character.age} ans" : "" %></p>
            <p><em>"<%= character.quotation %>"</em></p>
          </div>
        </div>
        <div class="character_description">
          <p><%= character.background %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="launch_adventure">
    <%= form_with url: new_storyroom_path, method: :get, id: "storyroom-form" do %>
      <%= hidden_field_tag :universe_id, @universe.id %>
      <%= hidden_field_tag :synopse_id, "", id: "synopse-id-field", "data-universe-target" => "synopseIdField" %>
      <%= hidden_field_tag :character_id, "", id: "character-id-field", "data-universe-target" => "characterIdField" %>
      <%= button_tag type: "submit", class: "floating-button" do %>
        <strong>+</strong><i class="fa-solid fa-feather"></i>
      <% end %>
    <% end %>
  </div>
</div>