config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :universes, only: %i[index show]
  resources :storyrooms, only: %i[index show new create edit update destroy] do
    resources :storyroom_characters, only: %i[new create edit update destroy]
    resources :messages, only: %i[create edit update]
    resources :storycards, only: %i[create destroy]
    resources :events, only: %i[create]
  end
  resources :history, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :universe_character_associations, dependent: :destroy
  has_many :universes, through: :universe_character_associations
  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :word
  belongs_to :storyroom
  validates :dice_value, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :storyroom
  belongs_to :user
  validates :content, presence: true
end

app/models/storycard.rb
class Storycard < ApplicationRecord
  belongs_to :storyroom
  validates :title, presence: true
end

app/models/storyroom.rb
class Storyroom < ApplicationRecord
  belongs_to :universe
  belongs_to :user
  # has_many :messages
  # has_many :storyroom_user_associations
  # has_many :users, through: :storyroom_user_associations
  # has_many :events
  # has_many :words, through: :events
  # has_many :storycards
  # has_many :storyroom_characters
  # validates :title, presence: true, uniqueness: { scope: :universe }
  # validates :user, presence: true
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :storycards, dependent: :destroy
  has_many :storyroom_characters, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: :universe }
end

app/models/storyroom_character.rb
class StoryroomCharacter < ApplicationRecord
  belongs_to :storyroom
  belongs_to :user
  validates :storyroom, presence: true
  validates :user, presence: true

  validates :user_id, uniqueness: { scope: :storyroom_id, message: "ne peut avoir qu'un seul personnage par storyroom" }
end

app/models/synopsis.rb
class Synopsis < ApplicationRecord
  belongs_to :universe
end

app/models/universe.rb
class Universe < ApplicationRecord
  # has_many :universe_word_associations
  # has_many :words, through: :universe_word_associations
  # has_many :universe_character_associations, dependent: :destroy
  # has_many :characters, through: :universe_character_associations
  has_many :words, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :synopses, dependent: :destroy
  validates :photo, presence: true
  validates :title, presence: true
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :storyroom_user_associations
  has_many :storyrooms, through: :storyroom_user_associations
  has_many :storyrooms
  has_many :storyroom_characters
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/models/word.rb
class Word < ApplicationRecord
  # has_many :universe_word_associations
  # has_many :universe, through: :universe_word_associations
  belongs_to :universe
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    @storyroom = Storyroom.find(params[:storyroom_id])
    @storycards = @storyroom.storycards
    @event = @storyroom.events.create
    @event.word = Word.find_by(title: @storycards.sample.title)
    @storycards.find_by(title: @event.word.title).destroy
    @event.dice_value = rand(1..20)
    @event.description = outcome(@event.dice_value)

    if @event.save
      redirect_to @storyroom
    else
      redirect_to @storyroom
    end
  end

  private

  def event_params
    params.require(:event).permit(:storyroom_id)
  end

  def outcome(dice_value)
    if dice_value <= 2
      'Echec critique'
    elsif dice_value <= 10
      'Négatif'
    elsif dice_value <= 18
      'Positif'
    elsif dice_value <= 20
      'Réussite critique'
    else
      'Neutre'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/storyrooms_helper.rb
module StoryroomsHelper
end

app/helpers/universes_helper.rb
module UniversesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar <%= 'hidden' if hidden %>">
    <%= link_to universes_path, class: "navbar_item #{current_page?(universes_path) ? "active" : ""}" do %>
      <i class="fa-solid fa-earth-europe"></i>
      <p>Univers</p>
    <% end %>
    <%= link_to storyrooms_path, class: "navbar_item #{current_page?(storyrooms_path) ? "active" : ""}" do %>
      <i class="fa-solid fa-feather"></i>
      <p>Récits</p>
    <% end %>
    <%= link_to history_index_path, class: "navbar_item #{current_page?(history_index_path) ? "active" : ""}" do %>
      <i class="fa-solid fa-book"></i>
      <p>Historique</p>
    <% end %>
</nav>

app/views/layouts/_topbar.html.erb
<nav class="topbar">
  <%= link_to root_path do %>
  <p>Assembly <i class="fa-solid fa-dice-d20"></i></p>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssemblyV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&display=swap" rel="stylesheet">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>

 </head>

  <body>
    <%= render'layouts/topbar' %>
    <%= yield %>

      <%= render'layouts/navbar',
      hidden: (controller_name == "storyrooms" && ["show", "new", "edit"].include?(action_name)) %>
  </body>
</html>

app/views/shared/_ios_pwa_links.html.erb
<!-- app/views/shared/_ios_pwa_links.html.erb -->
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">